-- =====================================================
-- 04_seed_properties.sql - Propriétés de test
-- =====================================================

INSERT INTO properties (
    id, agent_id, reference, title, description, transaction_type,
    address, neighborhood, city, district, postal_code, latitude, longitude,
    price, price_per_sqm, rent_price_monthly, rent_charges, charges_included, deposit,
    property_type, surface_area, rooms, bedrooms, bathrooms, toilets,
    floor_number, floors, has_cave, has_elevator, has_balcony, has_terrace, has_garden,
    has_parking, parking_spaces, has_garage, has_cellar, has_pool,
    has_alarm, has_intercom, has_digicode, has_caretaker,
    condition, orientation, is_furnished, is_quiet, has_view,
    heating_type, energy_rating, ges_rating, construction_year,
    available_from, virtual_tour_url, is_active, views_count
) VALUES

-- ==================== VENTES PARIS ====================

-- Property 1: Appartement Bastille (Agent Marie)
(
    '780b81ae-3ef4-4b4f-8ac0-092b3ca4c11b',
    '1937c11c-0796-40b9-a231-ab24332e23a1',
    'PAR-75011-001',
    'Bel appartement lumineux - Bastille',
    'Superbe appartement de 3 pièces au 4ème étage avec ascenseur, situé à deux pas de la Place de la Bastille. Séjour traversant très lumineux de 25m², cuisine équipée séparée, deux chambres avec parquet ancien en point de Hongrie. Salle de bains avec baignoire. Cave incluse. Copropriété bien entretenue. Proche métro Bastille (lignes 1, 5, 8), commerces et marchés. Idéal pour couple ou investissement locatif.',
    'sale',
    '25 rue de la Roquette',
    'Bastille',
    'Paris',
    '11ème arrondissement',
    '75011',
    48.8534,
    2.3716,
    485000,
    9700,
    NULL, NULL, FALSE, NULL,
    'apartment',
    50, 3, 2, 1, 1,
    4, 6, TRUE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, TRUE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'good', 'south_east', FALSE, FALSE, FALSE,
    'collective', 'D', 'E', 1925,
    '2026-02-01',
    NULL,
    TRUE, 156
),

-- Property 2: Appartement Passy luxe (Agent JP Martin)
(
    'd53e4ef6-5bf8-428a-9aa4-9d631b047f99',
    '18cb5033-07aa-431c-9c9d-2532fce5e258',
    'PAR-75016-001',
    'Appartement familial avec terrasse - Passy',
    'Magnifique appartement de 5 pièces dans un immeuble haussmannien de grand standing. Double séjour de 45m² avec cheminée en marbre et moulures d''époque, cuisine américaine équipée haut de gamme (Gaggenau), 3 chambres dont une suite parentale avec dressing et salle de bains privative. Terrasse de 15m² plein sud avec vue dégagée sur la Tour Eiffel. Gardien, digicode, parking en sous-sol inclus. Cave. Copropriété de luxe avec parties communes rénovées.',
    'sale',
    '12 avenue Paul Doumer',
    'Passy',
    'Paris',
    '16ème arrondissement',
    '75016',
    48.8582,
    2.2750,
    1850000,
    14230,
    NULL, NULL, FALSE, NULL,
    'apartment',
    130, 5, 3, 2, 2,
    5, 7, TRUE, FALSE, TRUE, FALSE,
    TRUE, 1, FALSE, TRUE, FALSE,
    TRUE, TRUE, TRUE, TRUE,
    'excellent', 'south', FALSE, TRUE, TRUE,
    'collective', 'C', 'C', 1890,
    '2026-03-01',
    'https://my360tour.com/passy-luxury',
    TRUE, 423
),

-- Property 3: Studio Montmartre (Agent Marie)
(
    '6fb71fbf-b34d-4613-8d8e-7f96d58cb084',
    '1937c11c-0796-40b9-a231-ab24332e23a1',
    'PAR-75018-001',
    'Studio rénové - Montmartre',
    'Charmant studio entièrement rénové au pied de la Butte Montmartre. Pièce principale lumineuse de 18m² avec cuisine équipée ouverte (plaques, frigo, micro-ondes), coin nuit séparé par une verrière. Salle d''eau moderne avec douche à l''italienne. Parquet massif. Double vitrage. Idéal investissement locatif ou pied-à-terre parisien. Proche métro Abbesses (ligne 12), restaurants et vie nocturne.',
    'sale',
    '8 rue Lepic',
    'Montmartre',
    'Paris',
    '18ème arrondissement',
    '75018',
    48.8844,
    2.3396,
    245000,
    12250,
    NULL, NULL, FALSE, NULL,
    'studio',
    20, 1, 0, 1, 1,
    3, 5, FALSE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, FALSE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'excellent', 'west', FALSE, FALSE, FALSE,
    'electric', 'E', 'D', 1920,
    '2026-01-15',
    NULL,
    TRUE, 89
),

-- Property 4: Loft Montreuil (Agent Marie)
(
    '718d7bb5-560a-406a-87ca-694ed54f5107',
    '1937c11c-0796-40b9-a231-ab24332e23a1',
    'MON-93100-001',
    'Loft d''artiste avec jardin - Montreuil',
    'Ancien atelier d''artiste transformé en loft exceptionnel de 150m². Volumes remarquables avec hauteur sous plafond de 4m et grande verrière industrielle. Espace de vie ouvert de 80m², mezzanine avec 2 chambres, 2 salles de bains. Jardin privatif de 50m² exposé sud-ouest. Possibilité d''exercer une activité libérale. Quartier Bas-Montreuil en pleine mutation, proche métro Robespierre. Coup de cœur assuré !',
    'sale',
    '12 rue de Paris',
    'Bas-Montreuil',
    'Montreuil',
    'Seine-Saint-Denis',
    '93100',
    48.8534,
    2.4488,
    650000,
    4333,
    NULL, NULL, FALSE, NULL,
    'loft',
    150, 4, 2, 2, 2,
    0, 2, FALSE, FALSE, TRUE, TRUE,
    TRUE, 2, FALSE, TRUE, FALSE,
    TRUE, FALSE, TRUE, FALSE,
    'good', 'south_west', FALSE, TRUE, TRUE,
    'individual', 'D', 'D', 1930,
    '2026-06-01',
    'https://my360tour.com/loft-montreuil',
    TRUE, 234
),

-- ==================== LOCATIONS PARIS ====================

-- Property 5: Location meublée Passy (Agent JP Martin)
(
    'a326dae9-b9f9-428b-9e79-2acbcc078c82',
    '18cb5033-07aa-431c-9c9d-2532fce5e258',
    'PAR-75016-LOC-001',
    '2 pièces meublé standing - Passy',
    'Appartement meublé haut de gamme dans immeuble de grand standing avec gardien 24h/24. Séjour lumineux de 22m², chambre séparée de 14m², cuisine équipée (lave-vaisselle, four, plaques induction), salle d''eau moderne. Mobilier design de qualité (Roche Bobois). Linge de maison fourni. Parfait pour expatrié ou mutation professionnelle. Disponible immédiatement. Bail mobilité possible.',
    'rent',
    '45 avenue Mozart',
    'Passy',
    'Paris',
    '16ème arrondissement',
    '75016',
    48.8555,
    2.2677,
    NULL, NULL,
    1800, 150, TRUE, 3600,
    'apartment',
    45, 2, 1, 1, 1,
    5, 7, TRUE, TRUE, FALSE, FALSE,
    FALSE, 0, FALSE, FALSE, FALSE,
    TRUE, TRUE, TRUE, TRUE,
    'excellent', 'west', TRUE, TRUE, TRUE,
    'collective', 'C', 'C', 1970,
    '2026-01-10',
    NULL,
    TRUE, 312
),

-- Property 6: Studio étudiant Quartier Latin (Agent Marie)
(
    '2015fc04-70e8-41f8-bd56-19970d464adf',
    '1937c11c-0796-40b9-a231-ab24332e23a1',
    'PAR-75005-LOC-001',
    'Studio meublé étudiant - Quartier Latin',
    'Studio meublé idéal pour étudiant, situé en plein cœur du Quartier Latin à proximité de la Sorbonne et du Panthéon. Kitchenette équipée, salle d''eau avec douche. Lit 140cm, bureau, rangements. Internet fibre inclus. Quartier vivant avec nombreux cafés, restaurants et librairies. Métro Luxembourg (RER B) à 3 minutes. Charges comprises (eau, chauffage, électricité plafonnée).',
    'rent',
    '15 rue Mouffetard',
    'Quartier Latin',
    'Paris',
    '5ème arrondissement',
    '75005',
    48.8462,
    2.3498,
    NULL, NULL,
    850, 0, TRUE, 850,
    'studio',
    18, 1, 0, 1, 1,
    2, 5, FALSE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, FALSE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'good', 'north', TRUE, FALSE, FALSE,
    'electric', 'E', 'D', 1960,
    '2026-01-01',
    NULL,
    TRUE, 567
),

-- ==================== VENTES LYON ====================

-- Property 7: Appartement Presqu'île Lyon (Agent Sophie)
(
    'bfcf9b00-007d-4203-942b-007353ac0855',
    '9c6645fa-6a35-46f7-8b6a-b5883862ae49',
    'LYO-69002-001',
    'Appartement bourgeois - Presqu''île',
    'Superbe appartement de caractère au cœur de la Presqu''île lyonnaise. Belles prestations d''origine : parquet point de Hongrie, cheminées en marbre, moulures. Séjour de 35m² très lumineux, cuisine séparée aménageable, 2 grandes chambres, salle de bains. Vue dégagée sur les toits de Lyon. À rafraîchir mais potentiel exceptionnel. Proche Place Bellecour et commerces. Parking possible à louer à proximité.',
    'sale',
    '28 rue de la République',
    'Presqu''île',
    'Lyon',
    '2ème arrondissement',
    '69002',
    45.7640,
    4.8357,
    420000,
    5250,
    NULL, NULL, FALSE, NULL,
    'apartment',
    80, 4, 2, 1, 1,
    4, 6, TRUE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, TRUE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'to_refresh', 'east', FALSE, FALSE, TRUE,
    'individual', 'E', 'E', 1885,
    '2026-04-01',
    NULL,
    TRUE, 178
),

-- Property 8: Maison Croix-Rousse (Agent Sophie)
(
    '4596e983-6f89-4c47-9717-20d1deeb6022',
    '9c6645fa-6a35-46f7-8b6a-b5883862ae49',
    'LYO-69004-001',
    'Maison de ville avec terrasse - Croix-Rousse',
    'Ravissante maison de ville de 120m² sur 3 niveaux dans le quartier authentique de la Croix-Rousse. RDC : entrée, salon/séjour de 30m² avec cheminée fonctionnelle, cuisine ouverte équipée. 1er étage : 2 chambres, salle de bains. 2ème étage : suite parentale avec terrasse de 20m² vue sur Lyon. Cave voûtée typique. Charme de l''ancien avec prestations modernes. Proche métro Croix-Rousse et marché.',
    'sale',
    '45 montée de la Grande Côte',
    'Croix-Rousse',
    'Lyon',
    '4ème arrondissement',
    '69004',
    45.7740,
    4.8280,
    580000,
    4833,
    NULL, NULL, FALSE, NULL,
    'house',
    120, 5, 3, 2, 2,
    0, 3, FALSE, FALSE, TRUE, FALSE,
    FALSE, 0, FALSE, TRUE, FALSE,
    TRUE, TRUE, TRUE, FALSE,
    'good', 'south', FALSE, TRUE, TRUE,
    'gas', 'D', 'D', 1900,
    '2026-05-01',
    'https://my360tour.com/croix-rousse-house',
    TRUE, 145
),

-- ==================== LOCATIONS LYON ====================

-- Property 9: T3 Part-Dieu (Agent Sophie)
(
    '0c2e7932-ea4e-4336-a337-01b51dc73417',
    '9c6645fa-6a35-46f7-8b6a-b5883862ae49',
    'LYO-69003-LOC-001',
    'T3 moderne proche Part-Dieu',
    'Bel appartement T3 dans résidence récente sécurisée. Séjour lumineux de 28m² avec balcon, cuisine équipée ouverte, 2 chambres avec placards, salle de bains avec douche et baignoire, WC séparé. Place de parking en sous-sol incluse. Idéal jeune couple ou colocation. À 5 minutes à pied de la gare Part-Dieu et du centre commercial. Transports : métro, tram, TGV.',
    'rent',
    '8 rue Garibaldi',
    'Part-Dieu',
    'Lyon',
    '3ème arrondissement',
    '69003',
    45.7607,
    4.8580,
    NULL, NULL,
    1200, 80, FALSE, 2400,
    'apartment',
    65, 3, 2, 1, 1,
    3, 8, TRUE, TRUE, FALSE, FALSE,
    TRUE, 1, FALSE, FALSE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'excellent', 'south_west', FALSE, FALSE, FALSE,
    'collective', 'B', 'B', 2018,
    '2026-02-01',
    NULL,
    TRUE, 234
),

-- ==================== VENTES MARSEILLE ====================

-- Property 10: Appartement Vieux-Port (Agent Lucas)
(
    '4cd19b24-3e11-439a-a8ad-d5af0b2c4b05',
    '22479295-f7bd-4d9a-bc9e-3d660d18a1f8',
    'MRS-13001-001',
    'Vue mer exceptionnelle - Vieux-Port',
    'Appartement d''exception avec vue panoramique sur le Vieux-Port et Notre-Dame de la Garde. Grand séjour de 40m² avec baies vitrées, terrasse de 12m², cuisine équipée séparée, 2 chambres, 2 salles de bains. Prestations haut de gamme : climatisation réversible, domotique, stores électriques. Parking sécurisé en sous-sol. Copropriété de standing avec piscine sur le toit. Emplacement rare !',
    'sale',
    '1 quai du Port',
    'Vieux-Port',
    'Marseille',
    '1er arrondissement',
    '13001',
    43.2965,
    5.3698,
    890000,
    8900,
    NULL, NULL, FALSE, NULL,
    'apartment',
    100, 4, 2, 2, 2,
    6, 8, TRUE, FALSE, TRUE, FALSE,
    TRUE, 1, FALSE, FALSE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    'excellent', 'south', FALSE, FALSE, TRUE,
    'individual', 'B', 'A', 2015,
    '2026-03-15',
    'https://my360tour.com/vieux-port-panorama',
    TRUE, 567
),

-- ==================== VENTES BORDEAUX ====================

-- Property 11: Échoppe bordelaise (Agent Camille)
(
    'ea771c5b-d25f-4518-91e5-8e2a9f7e7a01',
    'd15aaa6d-be7d-4f64-b677-f07ca75f1346',
    'BDX-33000-001',
    'Échoppe rénovée avec jardin - Chartrons',
    'Authentique échoppe bordelaise entièrement rénovée avec goût. Plain-pied de 95m² : entrée, séjour/salon de 35m² avec parquet ancien, cuisine ouverte équipée, 3 chambres, salle de bains moderne, buanderie. Jardin arboré de 80m² avec terrasse. Garage. Quartier très recherché des Chartrons, proche commerces de bouche, antiquaires et bords de Garonne. Coup de cœur !',
    'sale',
    '23 rue Notre-Dame',
    'Chartrons',
    'Bordeaux',
    'Gironde',
    '33000',
    44.8512,
    -0.5692,
    595000,
    6263,
    NULL, NULL, FALSE, NULL,
    'house',
    95, 4, 3, 1, 1,
    0, 1, FALSE, FALSE, FALSE, TRUE,
    TRUE, 1, TRUE, FALSE, FALSE,
    TRUE, FALSE, FALSE, FALSE,
    'excellent', 'south_west', FALSE, TRUE, FALSE,
    'gas', 'C', 'C', 1920,
    '2026-04-01',
    NULL,
    TRUE, 289
),

-- ==================== LOCATIONS BORDEAUX ====================

-- Property 12: Studio Gambetta (Agent Camille)
(
    'c46dd03f-1c46-4558-a5e8-cc21ba492e1f',
    'd15aaa6d-be7d-4f64-b677-f07ca75f1346',
    'BDX-33000-LOC-001',
    'Studio meublé - Place Gambetta',
    'Joli studio meublé au cœur de Bordeaux, à deux pas de la Place Gambetta. Pièce principale de 22m² avec coin cuisine équipée, coin nuit avec lit double, salle d''eau avec douche. Mobilier contemporain et fonctionnel. Internet fibre. Parfait pour étudiant ou jeune actif. Proche tous commerces, tram, et vie nocturne bordelaise. Disponible de suite.',
    'rent',
    '5 place Gambetta',
    'Centre-ville',
    'Bordeaux',
    'Gironde',
    '33000',
    44.8416,
    -0.5800,
    NULL, NULL,
    680, 40, FALSE, 680,
    'studio',
    22, 1, 0, 1, 1,
    3, 5, TRUE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, FALSE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'good', 'east', TRUE, FALSE, FALSE,
    'electric', 'D', 'D', 1975,
    '2026-01-01',
    NULL,
    TRUE, 156
),

-- ==================== VENTES NICE ====================

-- Property 13: Appartement Promenade des Anglais (Agent Emma)
(
    'b9a78f27-9d4d-48b9-b21e-b96f6c62e301',
    '4d5b94d4-2acf-4e8a-af7c-64d26f7d9a9c',
    'NIC-06000-001',
    'Vue mer Promenade des Anglais',
    'Somptueux appartement de 85m² sur la célèbre Promenade des Anglais avec vue mer imprenable. Séjour de 30m² ouvert sur grande terrasse de 20m², 2 chambres avec placards, salle de bains avec jacuzzi. Cuisine équipée haut de gamme. Climatisation réversible. Cave et parking privatif. Résidence de standing avec piscine et accès direct plage. Bien d''exception pour résidence principale ou investissement saisonnier.',
    'sale',
    '15 Promenade des Anglais',
    'Promenade des Anglais',
    'Nice',
    'Alpes-Maritimes',
    '06000',
    43.6947,
    7.2653,
    1250000,
    14705,
    NULL, NULL, FALSE, NULL,
    'apartment',
    85, 3, 2, 1, 1,
    4, 7, TRUE, FALSE, TRUE, FALSE,
    TRUE, 1, FALSE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    'excellent', 'south', FALSE, FALSE, TRUE,
    'individual', 'B', 'B', 2010,
    '2026-06-01',
    'https://my360tour.com/nice-promenade',
    TRUE, 678
),

-- ==================== LOCATIONS NICE ====================

-- Property 14: T2 Vieux Nice (Agent Emma)
(
    '7f42616f-2923-44c3-9950-37e3bbbc15af',
    '4d5b94d4-2acf-4e8a-af7c-64d26f7d9a9c',
    'NIC-06000-LOC-001',
    'T2 charme Vieux Nice',
    'Charmant T2 de 45m² au cœur du Vieux Nice, dans un immeuble typique niçois. Séjour avec cuisine ouverte équipée, chambre séparée avec rangements, salle d''eau. Tomettes anciennes et poutres apparentes. Quartier authentique et animé, à 3 minutes de la mer et du marché aux fleurs du Cours Saleya. Idéal location saisonnière ou résidence secondaire.',
    'rent',
    '8 rue de la Préfecture',
    'Vieux Nice',
    'Nice',
    'Alpes-Maritimes',
    '06000',
    43.6961,
    7.2750,
    NULL, NULL,
    950, 50, FALSE, 1900,
    'apartment',
    45, 2, 1, 1, 1,
    2, 4, FALSE, FALSE, FALSE, FALSE,
    FALSE, 0, FALSE, FALSE, FALSE,
    FALSE, TRUE, TRUE, FALSE,
    'good', 'north', FALSE, FALSE, FALSE,
    'electric', 'E', 'E', 1850,
    '2026-02-15',
    NULL,
    TRUE, 345
),

-- ==================== VITRY-SUR-SEINE ====================

-- Property 15: Maison Vitry (Agent Christian - non vérifié)
(
    '53fa9092-2e73-4d07-abcc-1db5da1c257b',
    '6deb05b1-f453-4667-8fe0-45372c20bea5',
    'VIT-94400-001',
    'Maison familiale avec jardin - Vitry',
    'Belle maison de ville de 110m² sur 3 niveaux avec jardin privatif de 60m². RDC : entrée, salon/séjour de 30m², cuisine équipée ouverte. 1er étage : 3 chambres, salle de bains. Sous-sol aménageable de 40m². Garage. Proche RER C (Vitry-sur-Seine) et futures lignes Grand Paris Express. Quartier calme et familial. Idéal pour première acquisition ou famille.',
    'sale',
    '15 rue Jean Jaurès',
    'Centre-ville',
    'Vitry-sur-Seine',
    'Val-de-Marne',
    '94400',
    48.7875,
    2.3928,
    385000,
    3500,
    NULL, NULL, FALSE, NULL,
    'house',
    110, 5, 3, 1, 2,
    0, 3, FALSE, FALSE, FALSE, TRUE,
    TRUE, 1, TRUE, TRUE, FALSE,
    FALSE, FALSE, FALSE, FALSE,
    'good', 'south', FALSE, TRUE, FALSE,
    'gas', 'D', 'D', 1965,
    '2026-03-01',
    NULL,
    TRUE, 123
);

SELECT 'Properties seeded successfully! Total: ' || COUNT(*) FROM properties;